steps:
  # 1. Build da imagem Docker usando o Dockerfile do repositório
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/qfomeai.com/qfomeai:$COMMIT_SHA'
      - '-t'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/qfomeai.com/qfomeai:latest'
      - '.'
    id: 'Build'

  # 2. Push da imagem construída para o Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/qfomeai.com/qfomeai'
    id: 'Push'

  # 3. Deploy no Google Cloud Run limpando as anotações legadas incompatíveis
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'qfomeai'
      - '--image'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/qfomeai.com/qfomeai:$COMMIT_SHA'
      - '--region'
      - 'us-west1'
      - '--clear-annotations'
      - 'run.googleapis.com/sources'
    id: 'Deploy'

images:
  - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/qfomeai.com/qfomeai:$COMMIT_SHA'
  - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/qfomeai.com/qfomeai:latest'

options:
  logging: CLOUD_LOGGING_ONLY
